name: earthcube
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.5
  - xarray=2022.3.0
  - netcdf4=1.5.8
  - pandas=1.4.2
  - jupyterlab=3.3.2
  - dask=2022.4.0
  - dask-labextension=5.2.0
  - pyarrow=7.0.0
  - awkward=1.8.0
  - numba=0.55.1
  - matplotlib=3.5.1
  - cartopy=0.20.2
  - cmocean=2.0
  - tqdm=4.64.0
